services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env.local
    volumes:
      - minio_data:/data

  equirect-shift:
    build: .
    depends_on:
      - minio
    ports:
      - "8000:8000"
    env_file:
      - .env.local

volumes:
  minio_data:
